Repository ros2/rclpy, pull requests merged in 2018-09, with the labels that each got.

#233 Get node names and namespaces
  rclpy/rclpy/node.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_node.py
Labels: in progress

#235 add getter for tuple with seconds and nanoseconds
  rclpy/rclpy/time.py
  rclpy/test/test_time.py
Labels: enhancement, in review

#237 Add methods on Mock class for Python 3.5 compatibility
  rclpy/test/mock_compat.py
  rclpy/test/test_clock.py
  rclpy/test/test_time_source.py
Labels: bug, in review

#238 Avoid repeated fini-ing on failure to parse yaml params
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#239 Don't use MethodType when monkey patching
  rclpy/test/mock_compat.py
Labels: bug, in review
