Repository ros2/rclpy, pull requests merged in 2018-04, with the labels that each got.

#182 Fix zero-initialization of rcl_arguments_t
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#176 Make rclpy.spin*() use a persistent executor
  rclpy/rclpy/__init__.py
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: bug, in review

#184 increase timeout as if this is running with connext as the default it…
  rclpy/CMakeLists.txt
Labels: in progress

#185 Node accepts command line args and can ignore global args
  rclpy/rclpy/__init__.py
  rclpy/rclpy/node.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_node.py
Labels: in review
