Repository ros2/rclpy, pull requests merged in 2018-08, with the labels that each got.

#210 TimeSource and support for ROS time
  rclpy/rclpy/clock.py
  rclpy/rclpy/node.py
  rclpy/rclpy/time_source.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_clock.py
  rclpy/test/test_node.py
  rclpy/test/test_time_source.py
Labels: in review

#216 executor.add_node() returns a bool
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: bug, in review

#217 Fix executor.remove_node()
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: bug, in review

#218 Node has a reference to its executor
  rclpy/rclpy/executors.py
  rclpy/rclpy/node.py
  rclpy/test/test_node.py
Labels: enhancement, in review

#220 Allow Duration to be negative
  rclpy/rclpy/duration.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_time.py
Labels: in review

#221 Allow duration to be initialized with negative nanoseconds
  rclpy/rclpy/duration.py
  rclpy/test/test_time.py
Labels: in review

#223 disable 1kHz test on all platforms
  rclpy/package.xml
  rclpy/test/test_timer.py
Labels: in review

#227 Bouncy patch2 backports
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: in review

#228 Add Node API method for setting the parameters_callback.
  rclpy/rclpy/node.py
  rclpy/test/test_parameters_callback.py
Labels: in review

#226 Publish parameter events
  rclpy/rclpy/node.py
  rclpy/rclpy/parameter.py
  rclpy/rclpy/parameter_service.py
  rclpy/rclpy/qos.py
  rclpy/test/test_destruction.py
Labels: in review

#230 Use consolidated rcl_wait_set_clear()
  rclpy/rclpy/executors.py
  rclpy/src/rclpy/_rclpy.c
Labels: enhancement, in review

#222 Callbacks when time jumps
  rclpy/rclpy/clock.py
  rclpy/rclpy/time_source.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_clock.py
  rclpy/test/test_time_source.py
Labels: enhancement, in review

#225 Take initial parameters from parameters yaml files and constructor arguments.
  rclpy/CMakeLists.txt
  rclpy/package.xml
  rclpy/rclpy/__init__.py
  rclpy/rclpy/node.py
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#234 Fix warning when parameter value is uninitialized.
  rclpy/src/rclpy/_rclpy.c
Labels: in review
