Repository ros2/rclpy, pull requests merged in 2019-04, with the labels that each got.

#297 Add param callback to time_source
  rclpy/rclpy/node.py
  rclpy/rclpy/time_source.py
  rclpy/test/test_time_source.py
Labels: in review

#304 Use rosgraph_msgs.msg.Clock for TimeSource
  rclpy/package.xml
  rclpy/rclpy/time_source.py
  rclpy/test/test_time_source.py
Labels: in review

#309 Executor exits immediately when shut down
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: in review

#310 Refresh nodes when executor is woken
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: in review

#311 Set QoS profile to default values (pre-QoS, standalone)
  rclpy/src/rclpy/_rclpy.c
Labels: in progress

#307 Refactor QoS Python-C conversion into less error-prone pattern (pre-QoS, standalone)
  rclpy/src/rclpy_common/src/common.c
Labels: in progress

#301 Add timeout to executor_spin_until_future_complete
  rclpy/rclpy/__init__.py
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: in review

#306 Add action graph API
  rclpy/CMakeLists.txt
  rclpy/rclpy/action/__init__.py
  rclpy/rclpy/action/graph.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/_rclpy_action.c
  rclpy/src/rclpy_common/include/rclpy_common/common.h
  rclpy/src/rclpy_common/src/common.c
  rclpy/test/action/test_graph.py
Labels: in review

#300 Rename action state transitions
  rclpy/rclpy/action/server.py
  rclpy/src/rclpy/_rclpy_action.c
  rclpy/test/action/test_server.py
Labels: in review

#315 add missing error handling and cleanup
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy_common/src/common.c
Labels: in review

#317 enforce correct message type is passed to various API
  rclpy/rclpy/action/client.py
  rclpy/rclpy/action/server.py
  rclpy/rclpy/client.py
  rclpy/rclpy/publisher.py
  rclpy/rclpy/service.py
  rclpy/test/action/test_client.py
  rclpy/test/action/test_server.py
  rclpy/test/test_client.py
  rclpy/test/test_messages.py
Labels: enhancement, in review

#318 Make destroy_subscription thread safe
  rclpy/CMakeLists.txt
  rclpy/rclpy/executors.py
  rclpy/rclpy/handle.py
  rclpy/rclpy/impl/implementation_singleton.py
  rclpy/rclpy/node.py
  rclpy/rclpy/subscription.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/_rclpy_pycapsule.c
  rclpy/test/test_destruction.py
  rclpy/test/test_waitable.py
Labels: in review

#320 Fix subscription pycapsule not being destroyed
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/_rclpy_pycapsule.c
Labels: bug, in review

#323 Remove __eq__ and __hash__ from Subscription
  rclpy/rclpy/subscription.py
Labels: bug, in review

#312 QoS - Expose Lifespan, Deadline, and Liveliness policy settings
  rclpy/rclpy/duration.py
  rclpy/rclpy/qos.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/_rclpy_action.c
  rclpy/src/rclpy_common/include/rclpy_common/common.h
  rclpy/src/rclpy_common/src/common.c
  rclpy/test/test_qos.py
Labels: in review

#324 Wait set uses pointers to rcl types not rcl->impl types
  rclpy/src/rclpy/_rclpy.c
Labels: bug, in review

#326 Prevent rcutils_log from accessing invalid memory
  rclpy/src/rclpy/_rclpy_logging.c
Labels: in progress

#329 Remove most of the timing checks in test_executor
  rclpy/test/test_executor.py
Labels: in review

#330 Make `destroy_node` thread safe
  rclpy/CMakeLists.txt
  rclpy/rclpy/action/client.py
  rclpy/rclpy/action/graph.py
  rclpy/rclpy/action/server.py
  rclpy/rclpy/client.py
  rclpy/rclpy/handle.py
  rclpy/rclpy/node.py
  rclpy/rclpy/subscription.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_destruction.py
  rclpy/test/test_handle.py
  rclpy/test/test_waitable.py
Labels: in review
