Repository ros2/rclpy, pull requests merged in 2019-05, with the labels that each got.

#319 Thread safe node.destroy_*
  rclpy/rclpy/action/server.py
  rclpy/rclpy/client.py
  rclpy/rclpy/clock.py
  rclpy/rclpy/executors.py
  rclpy/rclpy/guard_condition.py
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
  rclpy/rclpy/service.py
  rclpy/rclpy/signals.py
  rclpy/rclpy/timer.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_destruction.py
  rclpy/test/test_waitable.py
Labels: in review

#332 Use new test interface definitions
  rclpy/test/test_callback_group.py
  rclpy/test/test_destruction.py
  rclpy/test/test_messages.py
  rclpy/test/test_node.py
Labels: in review

#334 Ignore ValueError in SignalHandlerGuardCondition.__del__
  rclpy/rclpy/signals.py
Labels: bug, in review

#333 Make pub/sub/cli/srv/etc lists use @property on node
  rclpy/rclpy/node.py
  rclpy/test/test_destruction.py
Labels: in review

#337 API updates for RMW preallocation work.
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#335 Remove extra references to node handle
  rclpy/rclpy/client.py
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
  rclpy/rclpy/service.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_waitable.py
Labels: in review

#305 QoS - Minimal change for build against new rcl API
  rclpy/rclpy/executors.py
  rclpy/rclpy/waitable.py
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#313 QoS - Expose the assert_liveliness API for Publishers and Nodes
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#325 Parameter API enhancements
  rclpy/rclpy/__init__.py
  rclpy/rclpy/exceptions.py
  rclpy/rclpy/node.py
  rclpy/rclpy/parameter.py
  rclpy/rclpy/parameter_service.py
  rclpy/rclpy/time_source.py
  rclpy/rclpy/validate_parameter_name.py
  rclpy/test/test_node.py
  rclpy/test/test_parameters_callback.py
  rclpy/test/test_time_source.py
  rclpy/test/test_waitable.py
Labels: in progress

#338 Improve signal handling
  rclpy/src/rclpy/_rclpy_signal_handler.c
Labels: in review

#339 Setting automatic declaration for initial parameters to False.
  rclpy/rclpy/node.py
Labels: in review

#336 Wake executor when entities created or destroyed
  rclpy/CMakeLists.txt
  rclpy/rclpy/executors.py
  rclpy/rclpy/node.py
  rclpy/test/test_create_while_spinning.py
Labels: bug, in review

#340 Fix assert_liveliness use of node and publisher capsules
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
Labels: in review

#294 Update tests to include namespace in ROS types
  rclpy/test/test_action_graph.py
  rclpy/test/test_node.py
Labels: in review

#343 Ignore flake8 error 'imported but unused'
  rclpy/rclpy/__init__.py
  rclpy/rclpy/executors.py
Labels: in review

#316 QoS - API and implementation for Liveliness and Deadline event callbacks
  rclpy/CMakeLists.txt
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
  rclpy/rclpy/qos_event.py
  rclpy/rclpy/subscription.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/_rclpy_qos_event.c
  rclpy/src/rclpy_common/include/rclpy_common/common.h
  rclpy/test/test_qos_event.py
  rclpy/test/test_waitable.py
Labels: enhancement, in review

#344 Encourage users to always provide a QoS history depth
  rclpy/rclpy/action/client.py
  rclpy/rclpy/action/server.py
  rclpy/rclpy/node.py
  rclpy/rclpy/qos.py
  rclpy/rclpy/time_source.py
  rclpy/src/rclpy_common/src/common.c
  rclpy/test/test_action_client.py
  rclpy/test/test_action_server.py
  rclpy/test/test_callback_group.py
  rclpy/test/test_create_while_spinning.py
  rclpy/test/test_destruction.py
  rclpy/test/test_messages.py
  rclpy/test/test_node.py
  rclpy/test/test_qos.py
  rclpy/test/test_time_source.py
  rclpy/test/test_waitable.py
Labels: in review

#345 Parameter handling improvements.
  rclpy/rclpy/exceptions.py
  rclpy/rclpy/node.py
  rclpy/test/test_node.py
Labels: in progress

#346 update test since unicode characters are allowed now
  rclpy/test/test_messages.py
Labels: in review

#348 Update troubleshooting reference to index.ros.org
  rclpy/rclpy/impl/__init__.py
Labels: in review

#347 Parameter flexibility enhancements
  rclpy/rclpy/node.py
  rclpy/rclpy/parameter.py
  rclpy/rclpy/parameter_service.py
  rclpy/test/test_node.py
  rclpy/test/test_parameter.py
Labels: in progress

#349 Don't wrap QoS Event callback argument in a list
  rclpy/rclpy/qos_event.py
Labels: in progress

#351 Create RLock() early to avoid exception at shutdown
  rclpy/rclpy/handle.py
Labels: bug, in review

#355 destroy publishers after test is done
  rclpy/test/test_messages.py
Labels: in review

#354 Wait for nodes to discover each other in test_action_graph.py
  rclpy/test/test_action_graph.py
Labels: in review

#356 Initialize QoSProfile with values from rmw_qos_profile_default
  rclpy/rclpy/qos.py
  rclpy/test/test_qos.py
Labels: in review

#357 Enforcing parameter ranges.
  rclpy/rclpy/exceptions.py
  rclpy/rclpy/node.py
  rclpy/test/test_node.py
Labels: in review

#362 consolidate create_publisher arguments
  rclpy/rclpy/node.py
  rclpy/test/test_node.py
Labels: enhancement, in review

#363 Rename parameter options
  rclpy/rclpy/__init__.py
  rclpy/rclpy/node.py
  rclpy/test/test_node.py
Labels: in review
