Repository ros2/rclpy, pull requests merged in 2019-10, with the labels that each got.

#437 Action server: catch exception from user execute callback
  rclpy/rclpy/action/server.py
  rclpy/test/test_action_server.py
Labels: in review

#439 [dashing backport] Action server: catch exception from user execute callback (#437)
  rclpy/rclpy/action/server.py
  rclpy/test/test_action_server.py
Labels: in review

#442 [Dashing] Accept tuples as parameter arrays.
  rclpy/rclpy/parameter.py
  rclpy/test/test_parameter.py
Labels: in review

#443 Add Rate
  rclpy/CMakeLists.txt
  rclpy/rclpy/context.py
  rclpy/rclpy/exceptions.py
  rclpy/rclpy/handle.py
  rclpy/rclpy/node.py
  rclpy/rclpy/timer.py
  rclpy/test/test_rate.py
Labels: in review, needs review

#445 Drop rclpy test_remove_ros_args_empty test case.
  rclpy/test/test_utilities.py
Labels: enhancement

#441 Make use of Clock class for throttling logs
  rclpy/rclpy/impl/rcutils_logger.py
  rclpy/test/test_logging.py
Labels: enhancement

#452 add missing exec depend on rcl_interfaces
  rclpy/package.xml
Labels: bug, in review

#453 fix import to use builtin_interfaces.msg
  rclpy/rclpy/duration.py
  rclpy/rclpy/time.py
Labels: bug, in review
