Repository ros2/rclpy, pull requests merged in 2019-12, with the labels that each got.

#471 Fix test_action_client failures
  rclpy/test/test_action_client.py
Labels: in review

#473 [backport dashing] fix import to use builtin_interfaces.msg
  rclpy/rclpy/duration.py
  rclpy/rclpy/time.py
Labels: bug

#472 [backport dashing] add missing exec depend on rcl_interfaces
  rclpy/package.xml
Labels: bug

#467 [crystal backport] Send feedback callbacks properly in send_goal() of action client (#451)
  rclpy/rclpy/action/client.py
Labels: in review

#474 Guard against unexpected action responses
  rclpy/rclpy/action/client.py
Labels: bug, in review

#479 Use absolute topic name for rosout.
  rclpy/test/test_logging_rosout.py
Labels: in review

#480 Update constructor docstrings to use imperative mood.
  rclpy/rclpy/action/client.py
  rclpy/rclpy/action/server.py
  rclpy/rclpy/node.py
  rclpy/rclpy/qos_event.py
Labels: in review

#475 [dashing backport] Guard against unexpected action responses
  rclpy/rclpy/action/client.py
Labels: in review
