Repository ros2/rclpy, pull requests merged in 2019-11, with the labels that each got.

#456 Expressly destroy a node's objects before the node.
  rclpy/rclpy/node.py
Labels: in progress

#463 make short key of a QoS policy accessible
  rclpy/rclpy/qos.py
Labels: enhancement, in review

#461 Future invokes done callbacks when done
  rclpy/rclpy/task.py
  rclpy/test/test_task.py
Labels: bug, in review

#465 [eloquent backport] Send feedback callbacks properly in send_goal() of action client (#451)
  rclpy/rclpy/action/client.py
Labels: in review

#466 [dashing backport] Send feedback callbacks properly in send_goal() of action client (#451)
  rclpy/rclpy/action/client.py
Labels: in review

#458 Provide logging severity for string
  rclpy/rclpy/logging.py
  rclpy/src/rclpy/_rclpy_logging.c
  rclpy/test/test_logging.py
Labels: in review
