Repository ros2/rclpy, pull requests merged in 2019-03, with the labels that each got.

#280 Enable test using MultiThreadedExecutor
  rclpy/test/action/test_client.py
Labels: in review

#281 Guard against failed take when taking action messages
  rclpy/rclpy/action/client.py
  rclpy/rclpy/action/server.py
Labels: in review

#274 update to use separated action types
  rclpy/rclpy/action/client.py
  rclpy/rclpy/action/server.py
  rclpy/test/action/test_client.py
  rclpy/test/action/test_server.py
Labels: enhancement, in review

#283 update logger.warn (deprecated) to logger.warning
  rclpy/rclpy/action/server.py
  rclpy/test/test_logging.py
Labels: in review

#284 add RcutilsLogger.warning
  rclpy/rclpy/impl/rcutils_logger.py
Labels: bug, in review

#277 Improve documentation
  README.md
  rclpy/docs/Makefile
  rclpy/docs/make.bat
  rclpy/docs/source/about.rst
  rclpy/docs/source/api.rst
  rclpy/docs/source/api/actions.rst
  rclpy/docs/source/api/context.rst
  rclpy/docs/source/api/execution_and_callbacks.rst
  rclpy/docs/source/api/init_shutdown.rst
  rclpy/docs/source/api/logging.rst
  rclpy/docs/source/api/node.rst
  rclpy/docs/source/api/parameters.rst
  rclpy/docs/source/api/qos.rst
  rclpy/docs/source/api/services.rst
  rclpy/docs/source/api/timers.rst
  rclpy/docs/source/api/topics.rst
  rclpy/docs/source/api/utilities.rst
  rclpy/docs/source/conf.py
  rclpy/docs/source/examples.rst
  rclpy/docs/source/index.rst
  rclpy/package.xml
  rclpy/rclpy/__init__.py
  rclpy/rclpy/callback_groups.py
  rclpy/rclpy/client.py
  rclpy/rclpy/executors.py
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
  rclpy/rclpy/service.py
  rclpy/rclpy/subscription.py
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#286 Using ament_target_dependencies where possible
  rclpy/CMakeLists.txt
Labels: in review

#288 fix sigint guard condition's lifecycle bug
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#278 Improve error handling to avoid memory leaks in C extension
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#292 update tests to pass with numpy arrays
  rclpy/test/action/test_server.py
Labels: enhancement, in review

#298 fix sigint guard condition's lifecycle bug (#288)
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#299 Crystal patch 4 changelogs
  rclpy/CHANGELOG.rst
  rclpy/package.xml
Labels: in progress
