Repository ros2/rclpy, pull requests merged in 2020-08, with the labels that each got.

#612 Use absolute parameter events topic name
  rclpy/rclpy/node.py
Labels: enhancement

#596 Add ability to configure domain ID
  rclpy/rclpy/__init__.py
  rclpy/rclpy/context.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_init_shutdown.py
Labels: enhancement, in review

#615 skip test relying on source timestamps with Connext
  rclpy/test/test_client.py
  rclpy/test/test_node.py
Labels: bug

#605 MultiThreadedExecutor spin_until_future complete should not continue waiting when the future is done
  rclpy/rclpy/executors.py
Labels: bug, in review
