Repository ros2/rclpy, pull requests merged in 2020-07, with the labels that each got.

#595 [backport foxy] fix/improve error message failing to load C extension
  rclpy/rclpy/impl/__init__.py
Labels: bug, enhancement

#593 add QoSProfile.__str__
  rclpy/rclpy/qos.py
Labels: enhancement

#602 relax rate jitter test for individual periods
  rclpy/test/test_rate.py
Labels: bug

#601 Default incompatible qos callback should be set when there's no user specified callback
  rclpy/rclpy/qos_event.py
Labels: bug

#603 Destroy event handlers owned by publishers/subscriptions when calling publisher.destroy()/subscription.destroy()
  rclpy/rclpy/node.py
  rclpy/rclpy/publisher.py
  rclpy/rclpy/qos_event.py
  rclpy/rclpy/subscription.py
Labels: bug, in review
