Repository ros2/rclpy, pull requests merged in 2020-06, with the labels that each got.

#562 protect access to global logging calls with a mutex
  rclpy/CMakeLists.txt
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/detail/execute_with_logging_mutex.cpp
  rclpy/src/rclpy/detail/execute_with_logging_mutex.h
  rclpy/src/rclpy/detail/logging_mutex.cpp
  rclpy/src/rclpy/detail/logging_mutex.hpp
  rclpy/src/rclpy/detail/thread_safe_logging_output_handler.cpp
  rclpy/src/rclpy/detail/thread_safe_logging_output_handler.h
Labels: bug

#569 Doc+fix rclpy_handle_get_pointer_from_capsule()
  rclpy/src/rclpy_common/include/rclpy_common/handle.h
  rclpy/src/rclpy_common/src/handle.c
Labels: bug, documentation

#570 [Foxy Backport] Doc+fix rclpy_handle_get_pointer_from_capsule() (#569)
  rclpy/src/rclpy_common/include/rclpy_common/handle.h
  rclpy/src/rclpy_common/src/handle.c
Labels: bug, documentation

#571 Add `topic_name` property to Subscription
  rclpy/CMakeLists.txt
  rclpy/rclpy/subscription.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_subscription.py
Labels: enhancement

#573 add missing macro
  rclpy/src/rclpy/_rclpy.c
Labels: in review

#574 Fix executor behavior on shutdown
  rclpy/rclpy/executors.py
  rclpy/test/test_executor.py
Labels: bug

#572 Add message lost subscription event
  rclpy/rclpy/qos_event.py
  rclpy/src/rclpy/_rclpy_qos_event.c
Labels: enhancement, in review

#580 improve error message if rclpy C extensions are not found
  rclpy/rclpy/impl/__init__.py
Labels: enhancement

#579 fix moved troubleshooting url
  rclpy/rclpy/impl/__init__.py
Labels: bug
