Repository ros2/rclpy, pull requests merged in 2020-03, with the labels that each got.

#517 Included get_available_rmw_implementations
  rclpy/rclpy/utilities.py
Labels: enhancement

#519 [rclpy] fixed flake8 test utilities.py
  rclpy/rclpy/utilities.py
Labels: enhancement, tests

#497 Fix object destruction order
  rclpy/CMakeLists.txt
  rclpy/package.xml
  rclpy/rclpy/context.py
  rclpy/rclpy/executors.py
  rclpy/rclpy/guard_condition.py
  rclpy/rclpy/handle.py
  rclpy/rclpy/impl/implementation_singleton.py
  rclpy/rclpy/node.py
  rclpy/rclpy/qos_event.py
  rclpy/rclpy/timer.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/src/rclpy/_rclpy_action.c
  rclpy/src/rclpy/_rclpy_handle.c
  rclpy/src/rclpy/_rclpy_qos_event.c
  rclpy/src/rclpy/_rclpy_signal_handler.c
  rclpy/src/rclpy_common/include/rclpy_common/handle.h
  rclpy/src/rclpy_common/src/handle.c
  rclpy/src/test/rclpy_common/test_handle.cpp
  rclpy/test/test_destruction_order.py
  rclpy/test/test_handle.py
  rclpy/test/test_qos_event.py
  rclpy/test/test_waitable.py
Labels: bug

#522 add env var to filter available RMW implementations
  rclpy/rclpy/utilities.py
Labels: enhancement

#509 Add capability to publish serialized messages
  rclpy/rclpy/publisher.py
  rclpy/src/rclpy/_rclpy.c
  rclpy/test/test_messages.py
Labels: enhancement
