Repository ros2/rclpy, pull requests merged in 2021-08, with the labels that each got.

#800 Call Context._logging_fini() in Context.try_shutdown()
  rclpy/rclpy/context.py
Labels: bug

#818 👩‍🌾 Check that header is not none before accessing it in test
  rclpy/test/test_client.py
Labels: tests, Linux

#819 Add convert function from ParameterValue to Python builtin
  rclpy/rclpy/parameter.py
  rclpy/test/test_parameter.py
Labels: enhancement
