Repository ros2/rclpy, pull requests merged in 2021-12, with the labels that each got.

#863 Don't override `rclpy._rclpy_pybind11` docs
  rclpy/src/rclpy/_rclpy_logging.cpp
Labels: bug

#864 Add Clock.sleep_for using sleep_until
  rclpy/rclpy/clock.py
  rclpy/test/test_clock.py
Labels: enhancement

#849 print history and depth via topic info -v
  rclpy/rclpy/topic_endpoint_info.py
  rclpy/test/test_topic_endpoint_info.py
Labels: help wanted

#868 Make rclpy.try_shutdown() behavior to follow rclpy.shutdown() more closely
  rclpy/rclpy/__init__.py
  rclpy/rclpy/context.py
  rclpy/rclpy/utilities.py
Labels: enhancement

#865 Implement managed nodes
  rclpy/CMakeLists.txt
  rclpy/package.xml
  rclpy/rclpy/lifecycle/__init__.py
  rclpy/rclpy/lifecycle/managed_entity.py
  rclpy/rclpy/lifecycle/node.py
  rclpy/rclpy/lifecycle/publisher.py
  rclpy/rclpy/node.py
  rclpy/src/rclpy/_rclpy_pybind11.cpp
  rclpy/src/rclpy/lifecycle.cpp
  rclpy/src/rclpy/lifecycle.hpp
  rclpy/src/rclpy/service.cpp
  rclpy/src/rclpy/service.hpp
  rclpy/test/test_lifecycle.py
Labels: enhancement
